# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.


parameters:
    app_meta_extension.class: App\ResourceBundle\Twig\MetaExtension

services:
    app.twig.meta_extension:
        class: %app_meta_extension.class%
        arguments: [@aisel.settings.manager]
        tags:
            - { name: twig.extension }