# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    aisel_history_manager.class: Aisel\HistoryBundle\Manager\HistoryManager

services:
    sonata.admin.history:
        class: Aisel\HistoryBundle\Admin\HistoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "History", label: "Events" }
        arguments:
            - ~
            - Aisel\HistoryBundle\Entity\Event
            - ~
        calls:
            - [ setTranslationDomain, [forms]]
            - [ setManager, [@aisel.history.manager]]

    aisel.history.manager:
        class: %aisel_history_manager.class%
        arguments: [@service_container, @doctrine.orm.entity_manager]
