# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Aisel\HistoryBundle\Entity\Event:
    type: entity
    table: aisel_history_event
    repositoryClass: Aisel\HistoryBundle\Entity\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        entity_id:
            type: integer
            column: email
        entityType:
            type: integer
            column: entity_type
        eventType:
            type: integer
            column: event_type
        hits:
            type: integer
            column: hits
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
