# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_aisel_subscription_details:
    pattern:  /%website_api%/subscription.json
    defaults: { _controller: AiselSubscriptionBundle:ApiSubscription:subscriptionDetails, _format: json }
    requirements:
        _method: GET
